{"name": "test_014_issues_get_companies_with_limit_offset_and_status_company", "status": "failed", "statusDetails": {"message": "AssertionError: \u001b[31mFAILURE: \u001b[0mcheck 2 == 6: Ошибка! offset: 1. Ожидаемое значение 'company_id': 2, фактически значение 'company_id': 6\n\u001b[31mtest_companies.py\u001b[0m:378 in test_014_issues_get_companies_with_limit_offset_and_status_company() -> test_object_companies.validate_offset(1)\n\u001b[31mcompanies_methods.py\u001b[0m:50 in validate_offset() -> check.equal(first_company_id + offset_value, list_company_id_values[0],\n\n\u001b[31mFAILURE: \u001b[0mcheck CLOSED == ACTIVE: Ошибка! Ожидали 'company_status': ACTIVE, а получили CLOSED\n------------------------------------------------------------\nFailed Checks: 2", "trace": "\u001b[31mFAILURE: \u001b[0mcheck 2 == 6: Ошибка! offset: 1. Ожидаемое значение 'company_id': 2, фактически значение 'company_id': 6\n\u001b[31mtest_companies.py\u001b[0m:378 in test_014_issues_get_companies_with_limit_offset_and_status_company() -> test_object_companies.validate_offset(1)\n\u001b[31mcompanies_methods.py\u001b[0m:50 in validate_offset() -> check.equal(first_company_id + offset_value, list_company_id_values[0],\n\n\u001b[31mFAILURE: \u001b[0mcheck CLOSED == ACTIVE: Ошибка! Ожидали 'company_status': ACTIVE, а получили CLOSED\n------------------------------------------------------------\nFailed Checks: 2"}, "description": "\n    Это специальный тест, где мы получим заведомо не верный ответ от сервера.\n    Получение списка компаний с указанием limit=1 ,offset=1 и status_company = ACTIVE\n\n    Ожидаемый результат:\n        татус-код 200;\n        Время ответа сервера - не превышает 500ms;\n        Схема JSON-ответа соответствует Требованиям;\n        Response header \"Content-Type\": \"application/json\"\n        Response header \"Connection\": \"keep-alive\"\n\n    Полученный результат: падает валидация offset и company-status:\n        Ошибка! offset: 1. Ожидаемое значение 'company_id': 2, фактически значение 'company_id': 6\n        Ошибка! Ожидали 'company_status': ACTIVE, а получили CLOSED\n    ", "start": 1720619119704, "stop": 1720619119939, "uuid": "e8ba2150-dc77-4d35-87db-3e7eb3be5489", "historyId": "0f371c309a3ecffa7fde83ea3e461ed4", "testCaseId": "0f371c309a3ecffa7fde83ea3e461ed4", "fullName": "tests.companies.test_companies#test_014_issues_get_companies_with_limit_offset_and_status_company", "labels": [{"name": "tag", "value": "companies"}, {"name": "parentSuite", "value": "tests.companies"}, {"name": "suite", "value": "test_companies"}, {"name": "host", "value": "DESKTOP-OVBPB8C"}, {"name": "thread", "value": "332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.companies.test_companies"}]}